services:
  backend:
    image: jjsalustiano/backend-java:latest
    volumes:
      - /home/opc/app/wallet:/app/wallet:ro
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    restart: always

  frontend:
    image: jjsalustiano/frontend-react:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always