# ====== SERVER ======
server.port=8080

# ====== DATASOURCE ORACLE ======
spring.datasource.url=jdbc:oracle:thin:@dumplydb_high?TNS_ADMIN=/app/wallet
spring.datasource.username=ADMIN
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ====== JPA ======
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ====== LOG ======
logging.level.root=INFO
