# ====== SERVER ======
server.port=8080

# ====== DATASOURCE ORACLE ======
spring.datasource.url=jdbc:oracle:thin:@dumplydb_high
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# ====== JPA ======
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ====== LOG ======
logging.level.root=INFO
